# stereo_v54

inherit_from: config/train_test/ImpliCity-mono.yaml

dataset:
  satellite_image:  # orthorectified
    folder: data/source_data/ZUR1/Orthorectified_PAN
    pairs: ['18JAN29104120-P1BS-502980288020_01_P005.tif', '18MAR24105605-P1BS-501687882040_02_P006.tif']  # stereo
    normalize:  # image intensity
      mean: 1132.664
      std: 487.496

model:
  encoder2_kwargs:
    in_channel: 2  # num of input images (correspond to dataset)

training:
  run_name: ImpliCity-stereo_regress_MAE
  loss: MAE
  pretrained_encoder: True
  resume_scheduler: False
  resume_from: data/ImpliCity_demo/model/ImpliCity-stereo_pretrained.pt
  learning_rate: 0.001
  scheduler:
    type: MultiStepLR
    kwargs:
      gamma: 0.5
      milestones: [1000, 2000, 3000]

  visualize_every: 100
  save_vis_every: 100
  validate_every: 200
  checkpoint_every: 50
  backup_every: 1000

test:
  check_point: data/ImpliCity_demo/model/ImpliCity-stereo_pretrained.pt